# Generated by Django 4.1.4 on 2023-01-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bio',
            new_name='Biography',
        ),
    ]
