# Generated by Django 4.1.4 on 2023-01-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_bio_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secsub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('discription', models.TextField()),
            ],
        ),
    ]
